package net.cablen.caja.maquinaFiscal.modelo;

// Generated 25/10/2013 12:28:26 PM by Hibernate Tools 3.4.0.CR1

/**
 * MaquinasFiscales generated by hbm2java
 */
public class MaquinasFiscales implements java.io.Serializable {

	private int id;
	private String serial;

	public MaquinasFiscales() {
	}

	public MaquinasFiscales(int id, String serial) {
		this.id = id;
		this.serial = serial;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

}
