package net.cablen.contratos.modelo;

// Generated 04/10/2013 12:36:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import net.cablen.promotor.modelo.Promotores;

/**
 * ContratosPromotor generated by hbm2java
 */
public class ContratosPromotor implements java.io.Serializable {

	private Long id;
	private Promotores promotores;
	private long codigoContrato;
	private String fechaRegistro;
	private String fechaProceso;
	private String boxy;
	private int estatus;

	public ContratosPromotor() {
	}

	public ContratosPromotor(Promotores promotores, long codigoContrato,
			String fechaRegistro, String boxy, int estatus) {
		this.promotores = promotores;
		this.codigoContrato = codigoContrato;
		this.fechaRegistro = fechaRegistro;
		this.boxy = boxy;
		this.estatus = estatus;
	}

	public ContratosPromotor(Promotores promotores, long codigoContrato,
			String fechaRegistro, String fechaProceso, String boxy, int estatus) {
		this.promotores = promotores;
		this.codigoContrato = codigoContrato;
		this.fechaRegistro = fechaRegistro;
		this.fechaProceso = fechaProceso;
		this.boxy = boxy;
		this.estatus = estatus;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Promotores getPromotores() {
		return this.promotores;
	}

	public void setPromotores(Promotores promotores) {
		this.promotores = promotores;
	}

	public long getCodigoContrato() {
		return this.codigoContrato;
	}

	public void setCodigoContrato(long codigoContrato) {
		this.codigoContrato = codigoContrato;
	}

	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getFechaProceso() {
		return this.fechaProceso;
	}

	public void setFechaProceso(String fechaProceso) {
		this.fechaProceso = fechaProceso;
	}

	public String getBoxy() {
		return this.boxy;
	}

	public void setBoxy(String boxy) {
		this.boxy = boxy;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

}
