package net.cablen.soporte.cartera.recuperacion.modelo;

// Generated 25/11/2013 10:03:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import net.cablen.soporte.actividades.modelo.TshActividades;
import net.cablen.soporte.estatus.modelo.TshEstatus;

/**
 * Cartera generated by hbm2java
 */
public class Cartera implements java.io.Serializable {

	private long idCorrelativoCart;
	private TshEstatus tshEstatus;
	private TshActividades tshActividades;
	private String ticketCart;
	private String userSistema;
	private String fechaLlamada;
	private String comentarioInicial;
	private String comentarioFinal;
	private String fechaCierre;
	private String fechaCompromiso;
	private String abonado;
	private int estatus;
	private String detalle;
	
	public Cartera() {
	}

	public Cartera(long idCorrelativoCart, TshEstatus tshEstatus,
			TshActividades tshActividades, String ticketCart,
			String userSistema, String fechaLlamada, String comentarioInicial,
			String comentarioFinal, String fechaCierre, String fechaCompromiso,
			String abonado) {
		this.idCorrelativoCart = idCorrelativoCart;
		this.tshEstatus = tshEstatus;
		this.tshActividades = tshActividades;
		this.ticketCart = ticketCart;
		this.userSistema = userSistema;
		this.fechaLlamada = fechaLlamada;
		this.comentarioInicial = comentarioInicial;
		this.comentarioFinal = comentarioFinal;
		this.fechaCierre = fechaCierre;
		this.fechaCompromiso = fechaCompromiso;
		this.abonado = abonado;
	}

	public long getIdCorrelativoCart() {
		return this.idCorrelativoCart;
	}

	public void setIdCorrelativoCart(long idCorrelativoCart) {
		this.idCorrelativoCart = idCorrelativoCart;
	}

	public TshEstatus getTshEstatus() {
		return this.tshEstatus;
	}

	public void setTshEstatus(TshEstatus tshEstatus) {
		this.tshEstatus = tshEstatus;
	}

	public TshActividades getTshActividades() {
		return this.tshActividades;
	}

	public void setTshActividades(TshActividades tshActividades) {
		this.tshActividades = tshActividades;
	}

	public String getTicketCart() {
		return this.ticketCart;
	}

	public void setTicketCart(String ticketCart) {
		this.ticketCart = ticketCart;
	}

	public String getUserSistema() {
		return this.userSistema;
	}

	public void setUserSistema(String userSistema) {
		this.userSistema = userSistema;
	}

	public String getFechaLlamada() {
		return this.fechaLlamada;
	}

	public void setFechaLlamada(String fechaLlamada) {
		this.fechaLlamada = fechaLlamada;
	}

	public String getComentarioInicial() {
		return this.comentarioInicial;
	}

	public void setComentarioInicial(String comentarioInicial) {
		this.comentarioInicial = comentarioInicial;
	}

	public String getComentarioFinal() {
		return this.comentarioFinal;
	}

	public void setComentarioFinal(String comentarioFinal) {
		this.comentarioFinal = comentarioFinal;
	}

	public String getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(String fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public String getFechaCompromiso() {
		return this.fechaCompromiso;
	}

	public void setFechaCompromiso(String fechaCompromiso) {
		this.fechaCompromiso = fechaCompromiso;
	}

	public String getAbonado() {
		return this.abonado;
	}

	public void setAbonado(String abonado) {
		this.abonado = abonado;
	}

	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getDetalle() {
		return detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

}
