package net.cablen.bancos.modelo;

// Generated 04/11/2013 01:05:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * Bancos generated by hbm2java
 */
public class Bancos implements java.io.Serializable {

	private int idBanco;
	private String codigo;
	private String nombre;

	public Bancos() {
	}

	public Bancos(int idBanco, String codigo, String nombre) {
		this.idBanco = idBanco;
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public int getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(int idBanco) {
		this.idBanco = idBanco;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
