package net.cablen.recibos.modelo;

// Generated 16/11/2013 01:38:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DetalleRecibos generated by hbm2java
 */
public class DetalleRecibos implements java.io.Serializable {

	private Integer id;
	private RecibosPromotor recibosPromotor;
	private String abonado;
	private String titular;
	private String telefono;
	private float monto;
	private String userCaja;
	private String fechaProceso;
	private String userSistema;
	private String fechaRecibo;
	private int estatus;

	public DetalleRecibos() {
	}

	public DetalleRecibos(RecibosPromotor recibosPromotor, String abonado,
			String titular, String telefono, float monto, String userCaja,
			String fechaProceso, String userSistema, int estatus) {
		this.recibosPromotor = recibosPromotor;
		this.abonado = abonado;
		this.titular = titular;
		this.telefono = telefono;
		this.monto = monto;
		this.userCaja = userCaja;
		this.fechaProceso = fechaProceso;
		this.userSistema = userSistema;
		this.estatus = estatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RecibosPromotor getRecibosPromotor() {
		return this.recibosPromotor;
	}

	public void setRecibosPromotor(RecibosPromotor recibosPromotor) {
		this.recibosPromotor = recibosPromotor;
	}

	public String getAbonado() {
		return this.abonado;
	}

	public void setAbonado(String abonado) {
		this.abonado = abonado;
	}

	public String getTitular() {
		return this.titular;
	}

	public void setTitular(String titular) {
		this.titular = titular;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public String getUserCaja() {
		return this.userCaja;
	}

	public void setUserCaja(String userCaja) {
		this.userCaja = userCaja;
	}

	public String getFechaProceso() {
		return this.fechaProceso;
	}

	public void setFechaProceso(String fechaProceso) {
		this.fechaProceso = fechaProceso;
	}

	public String getUserSistema() {
		return this.userSistema;
	}

	public void setUserSistema(String userSistema) {
		this.userSistema = userSistema;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getFechaRecibo() {
		return fechaRecibo;
	}

	public void setFechaRecibo(String fechaRecibo) {
		this.fechaRecibo = fechaRecibo;
	}
	
	

}
