package net.cablen.recibos.modelo;

// Generated 16/11/2013 01:38:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import net.cablen.promotor.modelo.Promotores;

/**
 * RecibosPromotor generated by hbm2java
 */
public class RecibosPromotor implements java.io.Serializable {

	private Integer id;
	private long codigoRecibo;
	private Promotores promotor;
	private String fechaRegistro;
	private String fechaProceso;
	private int estatus;
	private Set detalleReciboses = new HashSet(0);

	public RecibosPromotor() {
	}

	public RecibosPromotor(long codigoRecibo, Promotores prom,
			String fechaRegistro, int estatus) {
		this.codigoRecibo = codigoRecibo;
		this.promotor = prom;
		this.fechaRegistro = fechaRegistro;
		this.estatus = estatus;
	}

	public RecibosPromotor(long codigoRecibo,  Promotores prom,
			String fechaRegistro, String fechaProceso, int estatus,
			Set detalleReciboses) {
		this.codigoRecibo = codigoRecibo;
		this.promotor = prom;
		this.fechaRegistro = fechaRegistro;
		this.fechaProceso = fechaProceso;
		this.estatus = estatus;
		this.detalleReciboses = detalleReciboses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public long getCodigoRecibo() {
		return this.codigoRecibo;
	}

	public void setCodigoRecibo(long codigoRecibo) {
		this.codigoRecibo = codigoRecibo;
	}


	public Promotores getPromotor() {
		return promotor;
	}

	public void setPromotor(Promotores promotor) {
		this.promotor = promotor;
	}

	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getFechaProceso() {
		return this.fechaProceso;
	}

	public void setFechaProceso(String fechaProceso) {
		this.fechaProceso = fechaProceso;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Set getDetalleReciboses() {
		return this.detalleReciboses;
	}

	public void setDetalleReciboses(Set detalleReciboses) {
		this.detalleReciboses = detalleReciboses;
	}

}
