package net.cablen.caja.conciliaciones.modelo;

// Generated 18/10/2013 02:46:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conciliaciones generated by hbm2java
 */
public class Conciliaciones implements java.io.Serializable {

	private int idConciliacion;
	private String userSistema;
	private String userCaja;
	private String fechaRegistro;
	private Float montoFinal;
	private String fechaCaja;
	private String facturaInicial;
	private String facturaFinal;
	private String reporteZ;
	private Float montoZ;
	private String maquinaFiscal;
	private Float difeMonto;
	private String detalleError;
	private Integer estatus;
	private String oficina;
	
	private Set referenciases = new HashSet(0);

	public Conciliaciones() {
	}

	public Conciliaciones(int idConciliacion, String userSistema) {
		this.idConciliacion = idConciliacion;
		this.userSistema = userSistema;
	}

	public Conciliaciones(int idConciliacion, String userSistema,
			String userCaja, String fechaRegistro,
			Float montoFinal, String fechaCaja, String facturaInicial,
			String facturaFinal, String reporteZ, Float montoZ,
			String maquinaFiscal, Float difeMonto, String detalleError,
			Integer estatus, Set referenciases) {
		this.idConciliacion = idConciliacion;
		this.userSistema = userSistema;
		this.userCaja = userCaja;
		this.fechaRegistro = fechaRegistro;
		this.montoFinal = montoFinal;
		this.fechaCaja = fechaCaja;
		this.facturaInicial = facturaInicial;
		this.facturaFinal = facturaFinal;
		this.reporteZ = reporteZ;
		this.montoZ = montoZ;
		this.maquinaFiscal = maquinaFiscal;
		this.difeMonto = difeMonto;
		this.detalleError = detalleError;
		this.estatus = estatus;
		this.referenciases = referenciases;
	}

	public int getIdConciliacion() {
		return this.idConciliacion;
	}

	public void setIdConciliacion(int idConciliacion) {
		this.idConciliacion = idConciliacion;
	}

	public String getUserSistema() {
		return this.userSistema;
	}

	public void setUserSistema(String userSistema) {
		this.userSistema = userSistema;
	}

	public String getUserCaja() {
		return this.userCaja;
	}

	public void setUserCaja(String userCaja) {
		this.userCaja = userCaja;
	}

	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}


	public Float getMontoFinal() {
		return this.montoFinal;
	}

	public void setMontoFinal(Float montoFinal) {
		this.montoFinal = montoFinal;
	}

	public String getFechaCaja() {
		return this.fechaCaja;
	}

	public void setFechaCaja(String fechaCaja) {
		this.fechaCaja = fechaCaja;
	}

	public String getFacturaInicial() {
		return this.facturaInicial;
	}

	public void setFacturaInicial(String facturaInicial) {
		this.facturaInicial = facturaInicial;
	}

	public String getFacturaFinal() {
		return this.facturaFinal;
	}

	public void setFacturaFinal(String facturaFinal) {
		this.facturaFinal = facturaFinal;
	}

	public String getReporteZ() {
		return this.reporteZ;
	}

	public void setReporteZ(String reporteZ) {
		this.reporteZ = reporteZ;
	}

	public Float getMontoZ() {
		return this.montoZ;
	}

	public void setMontoZ(Float montoZ) {
		this.montoZ = montoZ;
	}

	public String getMaquinaFiscal() {
		return this.maquinaFiscal;
	}

	public void setMaquinaFiscal(String maquinaFiscal) {
		this.maquinaFiscal = maquinaFiscal;
	}

	public Float getDifeMonto() {
		return this.difeMonto;
	}

	public void setDifeMonto(Float difeMonto) {
		this.difeMonto = difeMonto;
	}

	public String getDetalleError() {
		return this.detalleError;
	}

	public void setDetalleError(String detalleError) {
		this.detalleError = detalleError;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public Set getReferenciases() {
		return this.referenciases;
	}

	public void setReferenciases(Set referenciases) {
		this.referenciases = referenciases;
	}

	public String getOficina() {
		return oficina;
	}

	public void setOficina(String oficina) {
		this.oficina = oficina;
	}

	
	
}
