package net.cablen.oficinas.modelo;

// Generated 25/10/2013 03:56:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * Oficinas generated by hbm2java
 */
public class Oficinas implements java.io.Serializable {

	private int idOficina;
	private String oficina;
	private String punto;
	public Oficinas() {
	}

	public Oficinas(int idOficina, String oficina,String punto) {
		this.idOficina = idOficina;
		this.oficina = oficina;
		this.punto = punto;
	}

	public int getIdOficina() {
		return this.idOficina;
	}

	public void setIdOficina(int idOficina) {
		this.idOficina = idOficina;
	}

	public String getOficina() {
		return this.oficina;
	}

	public void setOficina(String oficina) {
		this.oficina = oficina;
	}

	public String getPunto() {
		return punto;
	}

	public void setPunto(String punto) {
		this.punto = punto;
	}

	
	
}
