package net.cablen.usuario.modelo;

// Generated 13-oct-2013 12:23:31 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Privilegios generated by hbm2java
 */
public class Privilegios implements java.io.Serializable {

	private int id;
	private String tipo;
	private String descripcion;
	private Set usuarioses = new HashSet(0);

	public Privilegios() {
	}

	public Privilegios(int id, String tipo, String descripcion) {
		this.id = id;
		this.tipo = tipo;
		this.descripcion = descripcion;
	}

	public Privilegios(int id, String tipo, String descripcion, Set usuarioses) {
		this.id = id;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.usuarioses = usuarioses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

}
