package net.cablen.permisos.modelo;

// Generated 15/10/2013 11:56:00 AM by Hibernate Tools 3.4.0.CR1

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

	private Integer id;
	private String formulario;
	private int idPrivilegio;

	public Permisos() {
	}

	public Permisos(String formulario, int idPrivilegio) {
		this.formulario = formulario;
		this.idPrivilegio = idPrivilegio;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFormulario() {
		return this.formulario;
	}

	public void setFormulario(String formulario) {
		this.formulario = formulario;
	}

	public int getIdPrivilegio() {
		return this.idPrivilegio;
	}

	public void setIdPrivilegio(int idPrivilegio) {
		this.idPrivilegio = idPrivilegio;
	}

}
