package net.cablen.precintos.modelo;

// Generated 11/11/2013 09:47:00 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import net.cablen.promotor.modelo.Promotores;

/**
 * PrecintosPromotor generated by hbm2java
 */
public class PrecintosPromotor implements java.io.Serializable {

	private long id;
	private String precinto;
	private String fechaRegistro;
	private String fechaProceso;
	private String boxy;
	private int estatus;
	private Promotores promotores;

	public PrecintosPromotor() {
	}

	public PrecintosPromotor(String precinto, Promotores promotor,
			String fechaRegistro, String fechaProceso, String boxy, int estatus) {
		this.precinto = precinto;
		this.promotores = promotor;
		this.fechaRegistro = fechaRegistro;
		this.fechaProceso = fechaProceso;
		this.boxy = boxy;
		this.estatus = estatus;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPrecinto() {
		return this.precinto;
	}

	public void setPrecinto(String precinto) {
		this.precinto = precinto;
	}

	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getFechaProceso() {
		return this.fechaProceso;
	}

	public void setFechaProceso(String fechaProceso) {
		this.fechaProceso = fechaProceso;
	}

	public String getBoxy() {
		return this.boxy;
	}

	public void setBoxy(String boxy) {
		this.boxy = boxy;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Promotores getPromotores() {
		return promotores;
	}

	public void setPromotores(Promotores promotores) {
		this.promotores = promotores;
	}
	
	

}
