package net.cablen.caja.estadoDeCuentas.modelo;

// Generated 16/10/2013 11:56:22 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EstadosCuenta generated by hbm2java
 */
public class EstadosCuenta implements java.io.Serializable {

	private String referencia;
	private String fechaPago;
	private String descripcion;
	private float monto;
	private String codBanco;
	private int estatus;

	public EstadosCuenta() {
	}

	public EstadosCuenta(String referencia, String fechaPago, String descripcion,
			float monto, String codBanco, int estatus) {
		this.referencia = referencia;
		this.fechaPago = fechaPago;
		this.descripcion = descripcion;
		this.monto = monto;
		this.codBanco = codBanco;
		this.estatus = estatus;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(String fechaPago) {
		this.fechaPago = fechaPago;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public String getCodBanco() {
		return this.codBanco;
	}

	public void setCodBanco(String codBanco) {
		this.codBanco = codBanco;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

}
