package net.cablen.soporte.estatus.modelo;

// Generated 25/11/2013 10:03:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TshEstatus generated by hbm2java
 */
public class TshEstatus implements java.io.Serializable {

	private int idEstatus;
	private String descripcion;
	private int estatus;
	private String categoria;
	
	private Set carteras = new HashSet(0);
	private Set troubleshootings = new HashSet(0);

	public TshEstatus() {
	}

	public TshEstatus(int idEstatus, String descripcion, int estatus) {
		this.idEstatus = idEstatus;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public TshEstatus(int idEstatus, String descripcion, int estatus,
			Set carteras, Set troubleshootings) {
		this.idEstatus = idEstatus;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.carteras = carteras;
		this.troubleshootings = troubleshootings;
	}

	public int getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(int idEstatus) {
		this.idEstatus = idEstatus;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Set getCarteras() {
		return this.carteras;
	}

	public void setCarteras(Set carteras) {
		this.carteras = carteras;
	}

	public Set getTroubleshootings() {
		return this.troubleshootings;
	}

	public void setTroubleshootings(Set troubleshootings) {
		this.troubleshootings = troubleshootings;
	}

	public String getCategoria() {
		return categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	
	

}
